### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by wengdunfang** [slf12/GRLModel#1]
Can you provide the dataset download address? like Baidu cloud?
Because I've read the code and found out that you've been manipulating the dataset.
think you.

**Comment by Mantha-Cheung** [comment]
> Can you provide the dataset download address? like Baidu cloud?
> Because I've read the code and found out that you've been manipulating the dataset.
> think you.

PETA：http://mmlab.ie.cuhk.edu.hk/projects/PETA.html
RAP：http://rap.idealtest.org/
You can download the PETA Dataset directly in its homepage, about RAP dataset, you need to send an agreement to  RAP's team-fellows, see the content of the link for details.

**Comment by wengdunfang** [comment]
> 
> 
> > Can you provide the dataset download address? like Baidu cloud?
> > Because I've read the code and found out that you've been manipulating the dataset.
> > think you.
> 
> PETA：http://mmlab.ie.cuhk.edu.hk/projects/PETA.html
> RAP：http://rap.idealtest.org/
> You can download the PETA Dataset directly in its homepage, about RAP dataset, you need to send an agreement to RAP's team-fellows, see the content of the link for details.

谢谢，我已经下下来，只不过我在inception/data/build_rap_region_data.py 101行代码：
tf.app.flags.DEFINE_string('labels_file', '/home/sangliufang/ijcai/inception/data/rap/rap_labels.txt', 'Labels file')
这里需要rap_label.txt，所以你是不是经过处理了，RAP数据集里没有这个文件。

**Comment by wengdunfang** [comment]
> 
> 
> > Can you provide the dataset download address? like Baidu cloud?
> > Because I've read the code and found out that you've been manipulating the dataset.
> > think you.
> 
> PETA：http://mmlab.ie.cuhk.edu.hk/projects/PETA.html
> RAP：http://rap.idealtest.org/
> You can download the PETA Dataset directly in its homepage, about RAP dataset, you need to send an agreement to RAP's team-fellows, see the content of the link for details.

I am sorry. Have you read the code？ in inception/data/build_rap_region_data.py  line 101 ,
tf.app.flags.DEFINE_string('labels_file', '/home/sangliufang/ijcai/inception/data/rap/rap_labels.txt', 'Labels file')
rap_label.txt , this file does not exist in the RAP dataset，so i think may the authors preprocessed the dataset

**Comment by Mantha-Cheung** [comment]
> > > Can you provide the dataset download address? like Baidu cloud?
> > > Because I've read the code and found out that you've been manipulating the dataset.
> > > think you.
> > 
> > 
> > PETA：http://mmlab.ie.cuhk.edu.hk/projects/PETA.html
> > RAP：http://rap.idealtest.org/
> > You can download the PETA Dataset directly in its homepage, about RAP dataset, you need to send an agreement to RAP's team-fellows, see the content of the link for details.
> 
> 谢谢，我已经下下来，只不过我在inception/data/build_rap_region_data.py 101行代码：
> tf.app.flags.DEFINE_string('labels_file', '/home/sangliufang/ijcai/inception/data/rap/rap_labels.txt', 'Labels file')
> 这里需要rap_label.txt，所以你是不是经过处理了，RAP数据集里没有这个文件。

我不是作者，只是也在跑这个模型，这个文件我是根据注释自己生成的，而且这个文件貌似仅用于生成TFRecord文件时在屏幕上打印一句话（inception/data/build_rap_region_data.py line422: print('Found %d JPEG files across %d labels inside %s.' %(len(filenames), len(unique_labels), data_dir)))

**Comment by wengdunfang** [comment]
> 
> 
> > > > Can you provide the dataset download address? like Baidu cloud?
> > > > Because I've read the code and found out that you've been manipulating the dataset.
> > > > think you.
> > > 
> > > 
> > > PETA：http://mmlab.ie.cuhk.edu.hk/projects/PETA.html
> > > RAP：http://rap.idealtest.org/
> > > You can download the PETA Dataset directly in its homepage, about RAP dataset, you need to send an agreement to RAP's team-fellows, see the content of the link for details.
> > 
> > 
> > 谢谢，我已经下下来，只不过我在inception/data/build_rap_region_data.py 101行代码：
> > tf.app.flags.DEFINE_string('labels_file', '/home/sangliufang/ijcai/inception/data/rap/rap_labels.txt', 'Labels file')
> > 这里需要rap_label.txt，所以你是不是经过处理了，RAP数据集里没有这个文件。
> 
> 我不是作者，只是也在跑这个模型，这个文件我是根据注释自己生成的，而且这个文件貌似仅用于生成TFRecord文件时在屏幕上打印一句话（inception/data/build_rap_region_data.py line422: print('Found %d JPEG files across %d labels inside %s.' %(len(filenames), len(unique_labels), data_dir)))

你能发一下你生成的这个文件给我一下吗？谢谢

**Comment by Mantha-Cheung** [comment]
> > > > > Can you provide the dataset download address? like Baidu cloud?
> > > > > Because I've read the code and found out that you've been manipulating the dataset.
> > > > > think you.
> > > > 
> > > > 
> > > > PETA：http://mmlab.ie.cuhk.edu.hk/projects/PETA.html
> > > > RAP：http://rap.idealtest.org/
> > > > You can download the PETA Dataset directly in its homepage, about RAP dataset, you need to send an agreement to RAP's team-fellows, see the content of the link for details.
> > > 
> > > 
> > > 谢谢，我已经下下来，只不过我在inception/data/build_rap_region_data.py 101行代码：
> > > tf.app.flags.DEFINE_string('labels_file', '/home/sangliufang/ijcai/inception/data/rap/rap_labels.txt', 'Labels file')
> > > 这里需要rap_label.txt，所以你是不是经过处理了，RAP数据集里没有这个文件。
> > 
> > 
> > 我不是作者，只是也在跑这个模型，这个文件我是根据注释自己生成的，而且这个文件貌似仅用于生成TFRecord文件时在屏幕上打印一句话（inception/data/build_rap_region_data.py line422: print('Found %d JPEG files across %d labels inside %s.' %(len(filenames), len(unique_labels), data_dir)))
> 
> 你能发一下你生成的这个文件给我一下吗？谢谢

邮箱?

**Comment by wengdunfang** [comment]
> 
> 
> > > > > > Can you provide the dataset download address? like Baidu cloud?
> > > > > > Because I've read the code and found out that you've been manipulating the dataset.
> > > > > > think you.
> > > > > 
> > > > > 
> > > > > PETA：http://mmlab.ie.cuhk.edu.hk/projects/PETA.html
> > > > > RAP：http://rap.idealtest.org/
> > > > > You can download the PETA Dataset directly in its homepage, about RAP dataset, you need to send an agreement to RAP's team-fellows, see the content of the link for details.
> > > > 
> > > > 
> > > > 谢谢，我已经下下来，只不过我在inception/data/build_rap_region_data.py 101行代码：
> > > > tf.app.flags.DEFINE_string('labels_file', '/home/sangliufang/ijcai/inception/data/rap/rap_labels.txt', 'Labels file')
> > > > 这里需要rap_label.txt，所以你是不是经过处理了，RAP数据集里没有这个文件。
> > > 
> > > 
> > > 我不是作者，只是也在跑这个模型，这个文件我是根据注释自己生成的，而且这个文件貌似仅用于生成TFRecord文件时在屏幕上打印一句话（inception/data/build_rap_region_data.py line422: print('Found %d JPEG files across %d labels inside %s.' %(len(filenames), len(unique_labels), data_dir)))
> > 
> > 
> > 你能发一下你生成的这个文件给我一下吗？谢谢
> 
> 邮箱?

wengdunfang@qq.com 谢谢

**Comment by slf12** [comment]
抱歉忘了放数据集label的顺序，不过rap_label.txt在代码里没有作用，空文件也行，主要是提醒了我rap数据集51个label的顺序还有peta数据集35个label的顺序在readme里面没有给，现在已经更新了，在百度云网盘上，链接: https://pan.baidu.com/s/16D1spNxN2SjZZR5l6v22Uw 提取码: iswu。

**Comment by PuNeal** [comment]
请问能够提供一下PETA数据集的标签文件吗？如果根据原始数据集中Label.txt文件来生成默认顺序（与原数据集中标注顺序一致）的标签文件，然后统计出来的各属性中正样本比例与您代码中中的weights基本一致，然而我根据您在百度网盘上分享的预测顺序列表统计出来的各属性正样本比例与您代码中的差别较大，具体如下：
您的代码中的weights：
 [0.5004, 0.3231, 0.1031, 0.0639, 0.1984, 0.1976, 0.8607,
 0.8520, 0.1380, 0.1343, 0.1016, 0.0700, 0.3058, 0.2945,
 0.0395, 0.2394, 0.5511, 0.2932, 0.0816, 0.7465, 0.2757, 
0.0265, 0.0774, 0.0199, 0.3627, 0.0336, 0.1440, 0.0443, 
0.2198, 0.0163, 0.0317, 0.5201, 0.0842, 0.4526, 0.0136]；
原始文件中标注顺序统计结果：
[0.4914, 0.3342, 0.1016, 0.0617, 0.1932, 0.2058, 0.8586,
0.8501, 0.1402, 0.1368, 0.1017, 0.0694, 0.3027, 0.3057,
0.0393, 0.2362, 0.5457, 0.2933, 0.0836, 0.7464, 0.2753,
0.0257, 0.0774, 0.0188, 0.3605, 0.0354, 0.1396, 0.0454,
 0.2101, 0.0163, 0.0306, 0.5188, 0.0822, 0.4579, 0.0125]；
根据网盘中提供的预测顺序统计结果：
[0.5485, 0.5009, 0.3207, 0.1049, 0.0627, 0.2348, 0.0849,
 0.0305, 0.0982, 0.7497, 0.1429, 0.0169, 0.0845, 0.4534,
 0.0119, 0.0389, 0.0269, 0.0697, 0.1325, 0.8535, 0.5172,
 0.0474, 0.3055, 0.0348, 0.8643, 0.134, 0.2149, 0.2920,
 0.0209, 0.3695, 0.1962, 0.2975, 0.2759, 0.0771, 0.1991]；
谢谢！

**Comment by wayyoungboy** [comment]
sorry, i can not open the website(RAP：http://rap.idealtest.org/).  Could you send me it? My E-mali is 1605581532@qq.com
抱歉，我用了很多办法都无法打开这个网站，是否能单独发给我一份呢？我的邮箱是 1605581532@qq.com
