### ISSUE TITLE
测试时的阈值设置

### ISSUE THREAD

**Issue by PuNeal** [slf12/GRLModel#3]
您好，我看到在测试代码里默认的阈值设置为0.5：softmax_or_not(predict, is_softmax=False, threshold=[0.5]*num_classes)。请问论文里在PETA数据集上的测得的各个指标的性能都是基于这个默认阈值吗？还是说对于每一个属性分类都在最佳阈值下测试？谢谢

**Comment by slf12** [comment]
默认阈值




| |
桑留芳
邮箱：slf12thuss@163.com
|

签名由 网易邮箱大师 定制

在2019年08月06日 09:26，PuNeal 写道：

您好，我看到在测试代码里默认的阈值设置为0.5：softmax_or_not(predict, is_softmax=False, threshold=[0.5]*num_classes)。请问论文里在PETA数据集上的测得的各个指标的性能都是基于这个默认阈值吗？还是说对于每一个属性分类都在最佳阈值下测试？谢谢

**Comment by PuNeal** [comment]
训练集中很多属性是不平衡的，大多数属性中以负样本居多，那么可以不使用0.5作为阈值吗？

**Comment by slf12** [comment]
可以的，可以针对不同属性找合适的阈值


| |
桑留芳
邮箱：slf12thuss@163.com
|

签名由 网易邮箱大师 定制

在2019年08月06日 13:45，PuNeal 写道：

训练集中很多属性是不平衡的，大多数属性中以负样本居多，那么可以不使用0.5作为阈值吗？
